apiVersion: v1
kind: Service
metadata:
  name: kafka-cluster-ip-service
spec:
  selector:
    component: kafka
  ports:
    - name: kafka
      protocol: TCP
      port: 9092
      targetPort: 9092
    - name: controller
      protocol: TCP
      port: 9093
      targetPort: 9093