apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-ssd-persistent-volume-claim
spec:
  storageClassName: ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
